### ISSUE TITLE
SSH connection unstable / reconnecting endlessly

### ISSUE THREAD

**Issue by datarian** [okteto/remote-kubernetes#165]
**Describe the bug**

I can successfully deploy a development POD in our company cluster.

Remote-SSH also initially succeeds at establishing a connection. However it is very unstable, painfully slow at best and usually crashes within less than 1 minute. 

**To Reproduce**
1. `Okteto: Up`
2. Wait for Remote-SSH window to open
3. Wait a few seconds, or open a file for editing / a Terminal on the host pod
4. I can then see a message reading: `Setting up SSH Host python-data-streaming.okteto: (details) Initializing VS Code Server`
5. This is followed by the screenshot
    
![image](https://user-images.githubusercontent.com/36982755/148344764-406f13e6-c32e-44f1-bc49-acbeebd17bff.png)

**Expected behavior**
A responsive, stable connection to the pod

**Desktop (please complete the following information):**
 - OS: OSX 12.0.1
 - VSCode 1.63.2
 - Remote - Kubernetes v0.3.4, Remote - SSH v0.70.0

**Manifest**

```yaml
name: python-data-streaming
image: okteto/python:3
context: ourk8scluster
namespace: ververica
command: bash
workdir: /code
sync:
  - ./code:/code
volumes:
- /root/.cache/pip
forward:
- 8080:8080
reverse:
- 9000:9000
autocreate: true
resources:
  requests:
    memory: "64Mi"
    cpu: "100m"
  limits:
    memory: "128Mi"
    cpu: "500m"
probes:
  liveness: true
  readiness: true
  startup: true
```

**Logs**

[pod.log](https://github.com/okteto/remote-kubernetes/files/7820292/pod.log)
[vscode_output.log](https://github.com/okteto/remote-kubernetes/files/7820293/vscode_output.log)
