### ISSUE TITLE
In development containers, environment variables are inherited from the base image, with the exception of PATH.

### ISSUE THREAD

**Issue by david9991** [okteto/remote-kubernetes#228]
**Description of the Issue**
In the development container, environment variables inherit from the base image by default, except the PATH variable which is overridden by Okteto.

**Steps to Reproduce**
Dockerfile:

```
FROM --platform=linux/amd64 rust as dev

RUN rustup target add aarch64-unknown-linux-gnu
RUN rustup toolchain install stable-aarch64-unknown-linux-gnu

```

okteto.yml:

```
namespace: okteto
build:
  testrust:
    dockerfile: Dockerfile
    image: xxx/testrust
    target: dev
dev:
  testrust:
    sync:
      - .:/usr/src/app
    image: ${OKTETO_BUILD_TESTRUST_IMAGE}
    autocreate: true

```

After building and running with Okteto, executing `rustup` for `cargo` in the development container was not possible because Okteto had overridden the PATH set in the rust base image.

**Expected behavior**
The specified PATH in the development container built by Okteto should be appended to the end of the PATH from the base image, instead of overriding it.

**Desktop (please complete the following information):**

- OS: macOS
- Version: 13.4

**Additional context**
